apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstageXXX
  description:
    test
  annotations:
    a:
     $text: https://github.com/AutoScout24/as24-dealer-users-management/tree/main
    b: 
     $text: https://github.com/AutoScout24/as24-dealer-users-management/tree/main/app
    conf: 
     $text: https://github.com/AutoScout24/as24-dealer-users-management/tree/main/conf
    project: 
     $text: https://github.com/AutoScout24/as24-dealer-users-management/tree/main/project
    ui: 
     $text: https://github.com/AutoScout24/as24-dealer-users-management/tree/main/ui
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
    lighthouse.com/website-url: https://backstage.io
spec:
  type: library
  owner: CNCFXX
  lifecycle: experimental
